<?php

/**
 * @file
 * Contains install- and update-related functions for the Webform Encrypt
 * module.
 */

/**
 * Implements hook_disable().
 */
function webform_encrypt_disable() {
  backdrop_set_message(t('Webform Encrypt has been disabled. However, all submitted data is still encrypted. Please !link to decrypt all data.', array(
    '!link' => l(t('uninstall the module'), 'admin/modules/uninstall'),
  )));
}

/**
 * Implements hook_uninstall().
 */
function webform_encrypt_uninstall() {
  config_clear('webform_encrypt.settings', 'webform_encrypt_match_user');

  // Decrypt all encrypted form values.
  $components = array();
  $results = db_query('SELECT nid, cid, extra FROM {webform_component}')->fetchAll();
  foreach ($results as $row) {
    $components[$row->nid . ':' . $row->cid] = unserialize($row->extra);
  }
  $data = db_query('SELECT nid, sid, cid, data FROM {webform_submitted_data}')->fetchAll();
  foreach ($data as $row) {
    $key = $row->nid . ':' . $row->cid;
    if (!empty($components[$key]['encrypt']) && is_array(@unserialize($row->data))) {
      db_update('webform_submitted_data')
        ->fields(array(
        'data' => decrypt($row->data, array('base64' => TRUE)),
      ))
        ->condition('nid', $row->nid)
        ->condition('sid', $row->sid)
        ->condition('cid', $row->cid)
        ->execute();
    }
  }
}

/**
 * Migrate webform_encrypt variables to config.
 */
function webform_encrypt_update_1000() {
  $config = config('webform_encrypt.settings');
  $config->set('webform_encrypt_match_user', update_variable_get('webform_encrypt_match_user', '0'));
  $config->save();

  update_variable_del('webform_encrypt_match_user');
}

/**
 * Implements hook_install().
 */
function webform_encrypt_install() {
  // Dynamically generated variable data was detected.
}
